/**
 * Developer Guide Data — AUTO-GENERATED
 *
 * Generated by: scripts/bundle-developer-guide.mjs
 * Source: spec/07-devtools-and-injection/developer-guide/ (11 files)
 * Generated: 2026-04-05T15:31:08.267Z
 *
 * Do NOT edit manually. Re-run the script to update.
 */

export const GUIDE_SECTION_COUNT = 11;

export const GUIDE_SECTIONS: readonly string[] = [
  // 00-guide-overview.md
  `# Rise Up Macro — Developer Guide Overview

> **Audience**: AI agents and human developers building standalone script projects for the Rise Up Macro Chrome extension.

---

## What This Guide Covers

This guide provides **everything** needed to create, build, and deploy a new standalone script project that integrates with the Rise Up Macro extension. After reading these documents, you will be able to:

1. Create a new project folder with the correct structure
2. Write an \`instruction.ts\` manifest that declares assets and seeding metadata
3. Use the \`marco.*\` SDK namespace to access extension services
4. Build the project using the TypeScript + LESS + Vite pipeline
5. Understand how scripts are injected into web pages
6. Test and debug your scripts in Chrome DevTools

## System Architecture (One Paragraph)

The Rise Up Macro extension injects standalone scripts into web pages via Chrome's \`chrome.scripting.executeScript\` API in the **MAIN** world. Each script project is a self-contained folder under \`standalone-scripts/\` with TypeScript source, an \`instruction.ts\` manifest, and compiled output in \`dist/\`. At build time, Vite compiles each project into an IIFE bundle and copies artifacts into the Chrome extension's \`dist/projects/scripts/{name}/\`. At runtime, a seeder reads \`instruction.json\` manifests and stores script metadata in \`chrome.storage.local\`. The injection pipeline resolves dependencies, loads assets in order (CSS → configs → templates → JavaScript), and exposes the frozen \`window.marco\` SDK namespace for inter-script communication via a postMessage bridge.

## Reading Order

| # | File | What You'll Learn |
|---|------|------------------|
| 00 | \`00-guide-overview.md\` | This file — orientation and architecture |
| 01 | \`01-project-structure.md\` | Folder layout, required files, naming conventions |
| 02 | \`02-instruction-schema.md\` | Full \`instruction.ts\` schema with examples |
| 03 | \`03-build-pipeline.md\` | How projects are compiled and deployed |
| 04 | \`04-sdk-namespace.md\` | Complete \`marco.*\` API reference |
| 05 | \`05-injection-lifecycle.md\` | How scripts are loaded and executed in the browser |
| 06 | \`06-seeding-system.md\` | How \`instruction.json\` drives seeding into storage |
| 07 | \`07-xpath-and-dom.md\` | XPath utilities and DOM interaction patterns |
| 08 | \`08-config-and-theme.md\` | Runtime config injection, theme system, LESS pipeline |
| 09 | \`09-testing-and-debugging.md\` | Testing scripts, debugging, common errors |
| 10 | \`10-examples.md\` | Complete examples: minimal and full-featured projects |

## System Paths

> **Dynamic placeholders** (resolved at export time):
> - Chrome extension root: \`chrome-extension://{EXTENSION_ID}/\`
> - Project scripts in extension: \`projects/scripts/\`
> - Build script: \`scripts/compile-instruction.mjs\`
> - Project root: \`{PROJECT_ROOT}\`
> - Standalone scripts: \`{PROJECT_ROOT}/standalone-scripts/\`

## Key Terminology

| Term | Meaning |
|------|---------|
| **Project** | A self-contained script unit under \`standalone-scripts/{name}/\` |
| **Instruction** | The \`instruction.ts\` manifest declaring assets and load order |
| **IIFE** | Immediately Invoked Function Expression — the compiled script format |
| **MAIN world** | Chrome's page execution context (shares DOM with the website) |
| **ISOLATED world** | Chrome's content script context (separate JS environment) |
| **Bridge** | The \`postMessage\` relay between MAIN and ISOLATED worlds |
| **Seeder** | The background process that stores script metadata on install |
| **SDK** | The \`window.marco\` namespace providing extension services |
| **slug** | Hyphen-case project ID (e.g., \`macro-controller\`) |
| **codeName** | PascalCase project key (e.g., \`MacroController\`) |
`,

  // 01-project-structure.md
  `# 01 — Project Structure

> How to organize a standalone script project.

---

## Folder Layout

Every project lives under \`standalone-scripts/{project-name}/\`:

\`\`\`
standalone-scripts/{project-name}/
├── src/
│   ├── index.ts              # Build entry point (compiled → dist/{name}.js)
│   ├── instruction.ts        # Load manifest (compiled → dist/instruction.json)
│   └── ...                   # Additional TypeScript source files
├── dist/                     # Compiled output (never edit directly)
│   ├── {name}.js             # IIFE bundle
│   ├── {name}.css            # Compiled LESS styles (optional)
│   ├── templates.json        # Compiled HTML templates (optional)
│   ├── instruction.json      # Compiled load manifest
│   └── ...                   # Configs, prompts, other assets
├── less/                     # LESS source files (optional)
├── templates/                # HTML template source files (optional)
├── prompts/                  # Prompt data files (optional)
└── README.md                 # Project documentation
\`\`\`

## Required Files

### 1. \`src/index.ts\` — Entry Point

The main TypeScript file that becomes the IIFE bundle. This is what executes in the browser.

\`\`\`typescript
// Minimal example
(function () {
    console.log("[my-project] Loaded");
    // Access SDK
    const token = await marco.auth.getToken();
})();
\`\`\`

### 2. \`src/instruction.ts\` — Project Manifest (Sole Source of Truth)

Declares **all** project metadata: name, version, dependencies, assets, seed configuration, and build output. Compiled to \`dist/instruction.json\` at build time. See \`02-instruction-schema.md\` for the full schema.

\`instruction.ts\` is the **only manifest file required** — no separate \`script-manifest.json\` is needed.

## Optional Directories

| Directory | Purpose | Output |
|-----------|---------|--------|
| \`less/\` | LESS stylesheets | \`dist/{name}.css\` |
| \`templates/\` | HTML template files | \`dist/templates.json\` |
| \`prompts/\` | Prompt data (JSON) | \`dist/prompts/\` |

## Naming Conventions

| What | Convention | Example |
|------|-----------|---------|
| Project folder | kebab-case | \`macro-controller\` |
| TypeScript files | camelCase | \`creditResolver.ts\` |
| CSS/LESS files | kebab-case | \`macro-looping.css\` |
| Config JSON files | kebab-case | \`macro-looping-config.json\` |
| Compiled output | matches project name | \`macro-controller.js\` |

## Rules

1. **\`src/\` is canonical** — never hand-edit files in \`dist/\`.
2. **\`dist/\` is the sole runtime input** — seeding and deployment read only from \`dist/\`.
3. **Legacy root-level JS files** (e.g., \`01-macro-looping.js\`) are off-limits — build automation must never read or write them.

## Project Identifiers

Each project has two derived identifiers:

| Field | Format | Example | Usage |
|-------|--------|---------|-------|
| \`slug\` | kebab-case | \`macro-controller\` | URLs, file paths, DB keys |
| \`codeName\` | PascalCase | \`MacroController\` | SDK namespace key (\`RiseupAsiaMacroExt.Projects.MacroController\`) |

Derivation: \`slug → codeName\` by capitalizing each segment after hyphens.
`,

  // 02-instruction-schema.md
  `# 02 — Instruction Schema Reference

> Complete \`instruction.ts\` schema with field-by-field documentation and examples.

---

## TypeScript Interface

\`\`\`typescript
interface ProjectInstruction {
    /** Schema version for forward-compatible evolution (e.g., "1.0") */
    schemaVersion: string;

    /** Project identifier — must match the folder name under standalone-scripts/ */
    name: string;

    /** Human-readable display name shown in extension UI */
    displayName: string;

    /** Semantic version (e.g., "2.1.0") */
    version: string;

    /** Brief description of the project's purpose */
    description: string;

    /** Chrome execution world: "MAIN" (shares page DOM) or "ISOLATED" (content script sandbox) */
    world: "MAIN" | "ISOLATED";

    /** Other project names that must be injected before this one */
    dependencies: string[];

    /** Global load order — lower values load first (xpath=1, macro-controller=2) */
    loadOrder: number;

    /** Asset declarations — determines the injection sequence */
    assets: {
        /** CSS files injected into <head> FIRST via chrome.scripting.insertCSS() */
        css: Array<{
            file: string;       // Filename in dist/ (e.g., "macro-looping.css")
            inject: "head";     // Always "head"
        }>;

        /** JSON config files loaded BEFORE JavaScript */
        configs: Array<{
            file: string;       // Filename in dist/ (e.g., "macro-looping-config.json")
            key: string;        // Runtime identifier (e.g., "config")
            injectAs?: string;  // Window global name (e.g., "__MARCO_CONFIG__")
        }>;

        /** JavaScript files loaded LAST, in declared order */
        scripts: Array<{
            file: string;           // Filename in dist/ (e.g., "macro-looping.js")
            order: number;          // Injection order within this project
            configBinding?: string; // Which config key this script needs
            themeBinding?: string;  // Which config key provides theme data
            isIife?: boolean;       // Whether the script is an IIFE wrapper (default: true)
        }>;

        /** Template registries loaded alongside configs */
        templates: Array<{
            file: string;       // Filename in dist/ (e.g., "templates.json")
            injectAs?: string;  // Window global name (e.g., "__MARCO_TEMPLATES__")
        }>;

        /** Prompt data files seeded into SQLite */
        prompts: Array<{
            file: string;       // Filename in dist/ (e.g., "prompts.json")
        }>;
    };
}
\`\`\`

## Injection Load Order

Assets are injected in this strict sequence:

1. **CSS** → injected into \`<head>\` via \`chrome.scripting.insertCSS()\`
2. **JSON configs** → fetched and injected as \`window\` globals
3. **Templates** → fetched and injected as \`window\` globals
4. **Prompts** → seeded into SQLite \`Prompts\` table
5. **JavaScript** → fetched and executed in declared \`order\`

## Example: Minimal Project (No Config)

\`\`\`typescript
const instruction: ProjectInstruction = {
    name: "xpath",
    displayName: "XPath Utilities",
    version: "1.0.0",
    description: "Global XPath utility library (getByXPath, findElement, reactClick)",
    world: "MAIN",
    dependencies: [],
    loadOrder: 1,
    assets: {
        css: [],
        configs: [],
        scripts: [
            { file: "xpath.js", order: 1, isIife: true },
        ],
        templates: [],
        prompts: [],
    },
};

export default instruction;
\`\`\`

## Example: Full-Featured Project (CSS, Configs, Templates)

\`\`\`typescript
const instruction: ProjectInstruction = {
    name: "macro-controller",
    displayName: "Macro Controller",
    version: "2.1.0",
    description: "Macro Controller for workspace and credit management",
    world: "MAIN",
    dependencies: ["xpath"],
    loadOrder: 2,
    assets: {
        css: [
            { file: "macro-looping.css", inject: "head" },
        ],
        configs: [
            { file: "macro-looping-config.json", key: "config", injectAs: "__MARCO_CONFIG__" },
            { file: "macro-theme.json", key: "theme", injectAs: "__MARCO_THEME__" },
        ],
        scripts: [
            { file: "macro-looping.js", order: 1, configBinding: "config", themeBinding: "theme", isIife: true },
        ],
        templates: [
            { file: "templates.json", injectAs: "__MARCO_TEMPLATES__" },
        ],
        prompts: [],
    },
};

export default instruction;
\`\`\`

## Compilation

\`\`\`bash
node scripts/compile-instruction.mjs standalone-scripts/{project-name}
\`\`\`

This reads \`src/instruction.ts\`, extracts the default export object literal, and writes \`dist/instruction.json\`.
`,

  // 03-build-pipeline.md
  `# 03 — Build Pipeline

> How projects are compiled, bundled, and deployed into the Chrome extension.

---

## Build Overview

When \`run.ps1 -d\` executes the full deploy pipeline:

\`\`\`
1. Auto-discover standalone-scripts/*/src/ folders
2. For each project:
   a. Compile instruction.ts → dist/instruction.json
   b. Compile LESS → dist/{name}.css (if less/ exists)
   c. Compile templates → dist/templates.json (if templates/ exists)
   d. Aggregate prompts → dist/prompts/macro-prompts.json
   e. TypeScript type-check (tsc --noEmit)
   f. Vite IIFE build → dist/{name}.js
3. Vite extension build:
   a. copyProjectScripts() → chrome-extension/dist/projects/scripts/{name}/
   b. Copy prompts → chrome-extension/dist/prompts/
   c. Generate seed-manifest.json → chrome-extension/dist/projects/seed-manifest.json
4. Extension boot:
   a. Seeder reads seed-manifest.json and stores metadata in chrome.storage.local
   b. reseedPrompts() wipes and re-inserts prompt data
5. At injection time:
   a. Read file paths from storage
   b. Fetch code via chrome.runtime.getURL(filePath)
   c. Inject in load order: CSS → configs → templates → JS
\`\`\`

## Individual Build Commands

| Command | What It Does |
|---------|-------------|
| \`npm run build:sdk\` | Compile marco-sdk IIFE |
| \`npm run build:{name}\` | Compile a specific project |
| \`npm run build:ext\` | Build Chrome extension (requires SDK pre-built) |

## Instruction Compilation

\`\`\`bash
node scripts/compile-instruction.mjs standalone-scripts/{project-name}
\`\`\`

- Reads \`src/instruction.ts\`
- Extracts the default export object literal
- Writes \`dist/instruction.json\`

## LESS Compilation

If a project has a \`less/\` directory:

\`\`\`
less/{name}.less → dist/{name}.css
\`\`\`

LESS variables map to CSS custom properties for runtime theming.

## Template Compilation

If a project has a \`templates/\` directory:

\`\`\`
templates/*.html → dist/templates.json
\`\`\`

Templates are aggregated into a single JSON registry, keyed by filename (without extension).

## Vite IIFE Build

Each project's \`src/index.ts\` is compiled by Vite into a self-contained IIFE:

- **Format**: IIFE (no module imports at runtime)
- **Target**: ES2020
- **Output**: \`dist/{name}.js\`
- **Config**: \`vite.config.sdk.ts\` (for marco-sdk) or project-specific Vite config

The IIFE format prevents scope pollution and ensures scripts work in Chrome's MAIN world without module loader support.

## Extension Deployment

The \`copyProjectScripts()\` Vite plugin copies compiled artifacts into the Chrome extension:

\`\`\`
standalone-scripts/{name}/dist/*
  → chrome-extension/dist/projects/scripts/{name}/*
\`\`\`

### Extension dist layout:

\`\`\`
chrome-extension/dist/
├── projects/
│   ├── scripts/
│   │   ├── marco-sdk/
│   │   │   ├── marco-sdk.js
│   │   │   └── instruction.json
│   │   ├── xpath/
│   │   │   ├── xpath.js
│   │   │   └── instruction.json
│   │   └── macro-controller/
│   │       ├── macro-looping.js
│   │       ├── macro-looping.css
│   │       ├── macro-looping-config.json
│   │       ├── macro-theme.json
│   │       ├── templates.json
│   │       └── instruction.json
│   └── seed-manifest.json
├── prompts/
│   └── macro-prompts.json
└── ...
\`\`\`

## Adding a New Project

1. Create \`standalone-scripts/{name}/src/index.ts\` and \`src/instruction.ts\`
2. Add \`build:{name}\` npm script in root \`package.json\`
3. The build pipeline auto-discovers and deploys it

> **Note:** \`instruction.ts\` is the sole manifest — no separate \`script-manifest.json\` is needed.

## Web Accessible Resources

All project artifacts are declared in \`manifest.json\`:

\`\`\`json
{
    "web_accessible_resources": [{
        "resources": [
            "projects/scripts/*/*",
            "projects/seed-manifest.json",
            "prompts/*"
        ],
        "matches": ["<all_urls>"]
    }]
}
\`\`\`

This allows the injection pipeline to \`fetch()\` script files at runtime.
`,

  // 04-sdk-namespace.md
  `# 04 — SDK Namespace Reference (\`marco.*\`)

> Complete API reference for the \`window.marco\` frozen namespace.

---

## Overview

The Marco SDK (\`window.marco\`) is a frozen namespace available to all scripts running in the MAIN world. It provides access to extension services via a postMessage bridge to the background service worker.

\`\`\`
MAIN world script
  → marco.auth.getToken()
  → window.postMessage({ source: "marco-sdk", type: "AUTH_GET_TOKEN", requestId })
  → Content Script relay (ISOLATED world)
  → chrome.runtime.sendMessage({ type: "AUTH_GET_TOKEN", requestId })
  → Background service worker
  → Response flows back the same chain
  → Promise resolves in MAIN world
\`\`\`

**Bridge timeout**: 15 seconds per request. All SDK methods (except sync ones) return Promises.

---

## \`marco.auth\` — Token Management

| Method | Returns | Description |
|--------|---------|-------------|
| \`getToken()\` | \`Promise<string \\| null>\` | Resolved bearer token from best source |
| \`getSource()\` | \`Promise<string>\` | Token source: \`"extension"\`, \`"localStorage"\`, \`"cookie"\`, \`"none"\` |
| \`refresh()\` | \`Promise<string \\| null>\` | Force re-resolve from all sources |
| \`isExpired()\` | \`Promise<boolean>\` | Check JWT \`exp\` claim vs current time |
| \`getJwtPayload()\` | \`Promise<Record<string, unknown> \\| null>\` | Decoded JWT payload (no verification) |
| \`getLastAuthDiag()\` | \`AuthResolutionDiag \\| null\` | Last token resolution diagnostic (sync) |

**Message types**: \`AUTH_GET_TOKEN\`, \`AUTH_GET_SOURCE\`, \`AUTH_REFRESH\`, \`AUTH_IS_EXPIRED\`, \`AUTH_GET_JWT\`

### Token Resolution Order

1. **Bridge** (extension relay) — fastest, preferred
2. **localStorage** (\`marco_bearer_token\`) — fallback if bridge times out (3s)
3. **None** — no token available

---

## \`marco.cookies\` — Cookie Access

| Method | Returns | Description |
|--------|---------|-------------|
| \`get(name)\` | \`Promise<string \\| null>\` | Raw cookie value by name |
| \`getDetail(name)\` | \`Promise<CookieDetail \\| null>\` | Full parsed cookie object |
| \`getAll()\` | \`Promise<CookieDetail[]>\` | All cookies for current domain |

\`\`\`typescript
interface CookieDetail {
    name: string;
    value: string;
    domain: string;
    path: string;
    expires: number | null;   // epoch ms, null = session
    secure: boolean;
    httpOnly: boolean;
    sameSite: "strict" | "lax" | "none";
}
\`\`\`

**Message types**: \`COOKIES_GET\`, \`COOKIES_GET_DETAIL\`, \`COOKIES_GET_ALL\`

---

## \`marco.config\` — Project Configuration

| Method | Returns | Description |
|--------|---------|-------------|
| \`get(key)\` | \`Promise<unknown>\` | Single config value |
| \`getAll()\` | \`Promise<Record<string, unknown>>\` | Full project config |
| \`set(key, value)\` | \`Promise<void>\` | Update config (persists to storage, broadcasts change) |
| \`onChange(callback)\` | \`void\` | Register listener for config changes |

**Reactivity**: When \`set()\` is called, the value persists and a \`CONFIG_CHANGED\` event broadcasts to all listeners registered via \`onChange()\`.

**Message types**: \`CONFIG_GET\`, \`CONFIG_GET_ALL\`, \`CONFIG_SET\`

---

## \`marco.xpath\` — XPath Evaluation

| Method | Returns | Description |
|--------|---------|-------------|
| \`get(key)\` | \`Promise<string \\| null>\` | Named XPath expression string |
| \`getAll()\` | \`Promise<Record<string, string>>\` | All XPath configs |
| \`resolve(key)\` | \`Element \\| null\` | Evaluate XPath → first matching element (**sync**) |
| \`resolveAll(key)\` | \`Element[]\` | Evaluate XPath → all matching elements (**sync**) |
| \`refreshCache()\` | \`Promise<void>\` | Re-fetch XPath map from background |

> **Note**: \`resolve()\` and \`resolveAll()\` are **synchronous** — they use a cached XPath map populated on SDK init. Call \`refreshCache()\` if XPaths change at runtime.

**Message types**: \`XPATH_GET\`, \`XPATH_GET_ALL\`

---

## \`marco.kv\` — Key-Value Storage

| Method | Returns | Description |
|--------|---------|-------------|
| \`get(key)\` | \`Promise<string \\| null>\` | Project-scoped KV value |
| \`set(key, value)\` | \`Promise<void>\` | Set KV pair |
| \`delete(key)\` | \`Promise<void>\` | Delete KV pair |
| \`list()\` | \`Promise<Array<{ key, value }>>\` | All KV pairs |

**Message types**: \`KV_GET\`, \`KV_SET\`, \`KV_DELETE\`, \`KV_LIST\`

---

## \`marco.files\` — File Storage

| Method | Returns | Description |
|--------|---------|-------------|
| \`save(path, content, mime?)\` | \`Promise<void>\` | Save file (base64 for binary) |
| \`read(path)\` | \`Promise<{ content, mime }>\` | Read file content |
| \`delete(path)\` | \`Promise<void>\` | Delete file |
| \`list()\` | \`Promise<FileEntry[]>\` | List all files |

\`\`\`typescript
interface FileEntry {
    filename: string;
    mimeType: string | null;
    size: number | null;
    createdAt: string;
}
\`\`\`

**Message types**: \`FILE_SAVE\`, \`FILE_READ\`, \`FILE_DELETE\`, \`FILE_LIST\`

---

## \`marco.notify\` — Toast Notifications

| Method | Returns | Description |
|--------|---------|-------------|
| \`toast(message, level?, opts?)\` | \`void\` | Show a toast (level: \`"info"\`, \`"warn"\`, \`"error"\`, \`"success"\`) |
| \`info(message, opts?)\` | \`void\` | Info toast shortcut |
| \`success(message, opts?)\` | \`void\` | Success toast shortcut |
| \`warning(message, opts?)\` | \`void\` | Warning toast shortcut |
| \`error(message, opts?)\` | \`void\` | Error toast shortcut |
| \`dismissAll()\` | \`void\` | Dismiss all visible toasts |
| \`onError(callback)\` | \`void\` | Register error listener |
| \`getRecentErrors()\` | \`RecentError[]\` | Get recent error history (max 50) |

**Toast behavior**:
- Max 3 visible, oldest auto-dismissed on overflow
- 5s deduplication window prevents toast storms
- Error toasts: 30s auto-dismiss; others: 12s
- Copy button includes version + timestamp

---

## \`marco.utils\` — Shared Utilities

| Method | Signature | Description |
|--------|-----------|-------------|
| \`withTimeout\` | \`<T>(promise, ms, fallback) → Promise<T>\` | Wrap a promise with a timeout |
| \`withRetry\` | \`<T>(fn, options) → Promise<T>\` | Retry async function with configurable backoff |
| \`createConcurrencyLock\` | \`<T>() → ConcurrencyLock<T>\` | Single-flight concurrency lock |
| \`delay\` | \`(ms) → Promise<void>\` | Promise-based delay |
| \`pollUntil\` | \`<T>(condition, options?) → Promise<T \\| null>\` | Poll until truthy or timeout |
| \`waitForElement\` | \`(options) → Promise<Element \\| null>\` | Wait for a DOM element to appear |
| \`debounce\` | \`(fn, ms) → fn\` | Debounce a function |
| \`throttle\` | \`(fn, ms) → fn\` | Throttle a function |
| \`safeJsonParse\` | \`<T>(json, fallback) → T\` | Safe JSON parse |
| \`formatDuration\` | \`(ms) → string\` | Human-readable duration |
| \`uid\` | \`(prefix?) → string\` | Short unique ID |
| \`deepClone\` | \`<T>(value) → T\` | Deep-clone plain objects |
| \`isObject\` | \`(value) → boolean\` | Check if non-null object |

---

## \`marco.prompts\` — Prompt Management

| Method | Returns | Description |
|--------|---------|-------------|
| \`getAll()\` | \`Promise<PromptEntry[]>\` | All prompts (cache-first with background revalidation) |
| \`save(prompt)\` | \`Promise<PromptEntry>\` | Save or update a prompt |
| \`delete(id)\` | \`Promise<void>\` | Delete prompt by ID |
| \`reorder(ids)\` | \`Promise<void>\` | Reorder prompts |
| \`inject(text, options?)\` | \`boolean\` | Inject text into page editor element |
| \`getConfig()\` | \`Promise<ResolvedPromptsConfig>\` | Resolved prompts config |
| \`invalidateCache()\` | \`Promise<void>\` | Clear in-memory + IndexedDB cache |
| \`preWarm()\` | \`Promise<PromptEntry[]>\` | Pre-warm cache for instant dropdown |

**Cache cascade**: in-memory → IndexedDB (stale-while-revalidate, 24h TTL) → extension bridge (with 3 retries).

---

## \`marco.api\` — HTTP API Client

| Method | Returns | Description |
|--------|---------|-------------|
| \`call(path, options?)\` | \`Promise<ApiResponse>\` | Call endpoint by path (e.g., \`"credits.fetchWorkspaces"\`) |
| \`credits.fetchWorkspaces(options?)\` | \`Promise<ApiResponse>\` | Typed: fetch all workspaces |
| \`credits.fetchBalance(wsId, options?)\` | \`Promise<ApiResponse>\` | Typed: workspace credit balance |
| \`credits.resolve(wsId, options?)\` | \`Promise<ApiResponse>\` | Typed: resolve with fallback |
| \`workspace.move(projectId, targetWsId, options?)\` | \`Promise<ApiResponse>\` | Typed: move project |
| \`workspace.rename(wsId, newName, options?)\` | \`Promise<ApiResponse>\` | Typed: rename workspace |
| \`workspace.markViewed(projectId, options?)\` | \`Promise<ApiResponse>\` | Typed: mark viewed |
| \`workspace.probe(options?)\` | \`Promise<ApiResponse>\` | Typed: connectivity check |
| \`workspace.resolveByProject(projectId, options?)\` | \`Promise<ApiResponse>\` | Typed: resolve workspace |

The API module uses an Axios instance with automatic bearer token injection, 401 recovery (token refresh), and 429 retry with backoff.

---

## Per-Project Namespace

Each project also gets a project-scoped namespace:

\`\`\`javascript
window.RiseupAsiaMacroExt.Projects.{CodeName}.vars.get(key)
window.RiseupAsiaMacroExt.Projects.{CodeName}.vars.set(key, value)
window.RiseupAsiaMacroExt.Projects.{CodeName}.cookies.get(bindTo)
window.RiseupAsiaMacroExt.Projects.{CodeName}.kv.get(key)
window.RiseupAsiaMacroExt.Projects.{CodeName}.meta    // { name, version, slug, codeName }
window.RiseupAsiaMacroExt.Projects.{CodeName}.log.info(msg)
\`\`\`

## Message Type Naming Convention

All background message types use **SCREAMING_SNAKE_CASE**:

\`\`\`
AUTH_GET_TOKEN       (not auth-get-token)
COOKIES_GET_DETAIL   (not cookie_get_detail)
CONFIG_SET           (not configSet)
\`\`\`
`,

  // 05-injection-lifecycle.md
  `# 05 — Injection Lifecycle

> How scripts are loaded and executed in the browser.

---

## 7-Stage Lifecycle

### Stage 1: Dependency Resolution

1. Background reads script entries from \`chrome.storage.local\`
2. \`resolveDependencies()\` scans each script's \`dependencies[]\`
3. Missing dependencies are auto-resolved from the script store
4. All scripts are topologically sorted by \`loadOrder\` (lower = first)
5. Circular dependencies throw a hard error with the cycle path logged

### Stage 2: Namespace Bootstrapping

\`\`\`javascript
window.RiseupAsiaMacroExt ??= { Projects: {} };
\`\`\`

The root namespace is created if it doesn't exist. Each project registers its sub-namespace under \`Projects.{CodeName}\`.

### Stage 3: Relay Installation

The content script relay is installed in the ISOLATED world. It listens for \`postMessage\` events from the MAIN world and forwards them to the background via \`chrome.runtime.sendMessage\`.

### Stage 4: IIFE Execution

Scripts are injected via \`chrome.scripting.executeScript\` with \`world: "MAIN"\`. Each script is a self-contained IIFE — no module imports at runtime.

### Stage 5: Script-to-Script Communication

Scripts communicate via the shared \`window.RiseupAsiaMacroExt\` namespace and the \`marco.*\` SDK. The SDK is always injected first (loadOrder: 0).

### Stage 6: CSP Fallback Handling

If Content Security Policy blocks \`chrome.scripting.executeScript\`, the system falls back to injecting via a \`<script>\` element with the code as \`textContent\`.

### Stage 7: Dynamic Loading (Runtime)

Scripts can be dynamically loaded at runtime via the injection handler. This supports hot-reloading during development.

---

## Asset Injection Order

For each project, assets are injected in this strict sequence:

\`\`\`
1. CSS          → chrome.scripting.insertCSS({ files: [...] })
2. JSON configs → fetch() → inject as window.__MARCO_CONFIG__ = {...}
3. Templates    → fetch() → inject as window.__MARCO_TEMPLATES__ = {...}
4. Prompts      → seeded into SQLite (background process)
5. JavaScript   → chrome.scripting.executeScript({ files: [...] })
\`\`\`

## Cross-Project Ordering

Projects are injected in \`loadOrder\` sequence:

| Project | loadOrder | Dependencies |
|---------|-----------|-------------|
| marco-sdk | 0 | none |
| xpath | 1 | none |
| macro-controller | 2 | xpath |

The SDK (\`marco-sdk\`) always loads first because it creates \`window.marco\` which all other projects depend on.

## Path Resolution

Scripts store **file paths** in storage, not embedded code. At injection time:

\`\`\`javascript
if (script.isAbsolute) {
    url = script.filePath;                          // Use as-is (external URL)
} else {
    url = chrome.runtime.getURL(script.filePath);   // Resolve relative to extension
}
// Fetch code from URL; fallback to script.code if fetch fails
\`\`\`

### Example stored paths:

| Script | FilePath | IsAbsolute |
|--------|----------|------------|
| \`xpath.js\` | \`projects/scripts/xpath/xpath.js\` | 0 |
| \`macro-looping.js\` | \`projects/scripts/macro-controller/macro-looping.js\` | 0 |

## Settings

| Key | Value | Purpose |
|-----|-------|---------|
| \`ExtensionBasePath\` | \`chrome-extension://{id}/\` | Base URL for resolving relative file paths |
`,

  // 06-seeding-system.md
  `# 06 — Seeding System

> How \`instruction.json\` and \`seed-manifest.json\` drive automatic script registration.

---

## Overview

Seeding is the process of registering scripts, configs, and project metadata into \`chrome.storage.local\` so the injection pipeline knows what to load and where to find it. The system uses a **declarative manifest** generated at build time.

## Seed Manifest

At build time, \`scripts/generate-seed-manifest.mjs\` scans all projects and generates:

\`\`\`
chrome-extension/dist/projects/seed-manifest.json
\`\`\`

### Manifest Structure

\`\`\`json
{
    "version": "1.0.0",
    "generatedAt": "2026-04-03T...",
    "projects": [
        {
            "name": "xpath",
            "displayName": "XPath Utilities",
            "version": "1.0.0",
            "description": "...",
            "basePath": "projects/scripts/xpath",
            "isGlobal": true,
            "isRemovable": false,
            "loadOrder": 1,
            "dependencies": [],
            "targetUrls": ["*"],
            "scripts": [
                {
                    "id": "default-xpath",
                    "file": "xpath.js",
                    "name": "XPath Utilities",
                    "version": "1.0.0",
                    "world": "MAIN",
                    "isIife": true
                }
            ],
            "configs": [],
            "css": [],
            "templates": []
        }
    ]
}
\`\`\`

## How Seeding Works

1. **On extension install/update**, the background service worker calls \`seedFromManifest()\`
2. The seeder fetches \`seed-manifest.json\` via \`chrome.runtime.getURL()\`
3. For each project in the manifest:
   - **Scripts** → upserted into storage with file paths (not embedded code)
   - **Configs** → upserted with JSON content fetched from extension files
   - **CSS** → registered for \`chrome.scripting.insertCSS()\` injection
   - **Templates** → registered for window global injection
4. Upsert is **idempotent** — re-running the seeder with the same manifest produces no changes

## Storage Schema

### Scripts

\`\`\`typescript
interface StoredScript {
    id: string;
    name: string;
    version: string;
    filePath: string;       // Relative to extension root
    isAbsolute: number;     // 0 = relative, 1 = absolute URL
    isEnabled: number;
    world: "MAIN" | "ISOLATED";
    loadOrder: number;
    dependencies: string;   // JSON array of project names
}
\`\`\`

### Configs

\`\`\`typescript
interface StoredConfig {
    id: string;
    name: string;
    key: string;
    content: string;        // JSON string of the config data
    injectAs?: string;      // Window global name
}
\`\`\`

## Adding a New Project to Seeding

Simply create a valid \`instruction.ts\` with a \`seed\` block in your project's \`src/\` folder. The build pipeline will:

1. Compile \`instruction.ts\` → \`dist/instruction.json\`
2. Include the project in \`seed-manifest.json\` generation
3. Copy artifacts to \`chrome-extension/dist/projects/scripts/{name}/\`

No seeder code modifications needed — the manifest-driven system discovers projects automatically.

> **Note:** \`instruction.ts\` is the sole manifest — no separate \`script-manifest.json\` is required.

## Prompt Seeding

Prompts follow a separate path:

1. Aggregated from \`standalone-scripts/prompts/\` → \`dist/prompts/macro-prompts.json\`
2. Deployed to \`chrome-extension/dist/prompts/\`
3. On boot: **full wipe + reseed** — all rows cleared from Prompts tables, then re-inserted
4. User-created prompts are **not preserved** across deployments
`,

  // 07-xpath-and-dom.md
  `# 07 — XPath & DOM Interaction Patterns

> How to find, click, and interact with DOM elements in injected scripts.

---

## SDK XPath Methods

The \`marco.xpath\` module provides cached XPath evaluation:

\`\`\`javascript
// Get a named XPath expression
const xpath = await marco.xpath.get("chatBox");

// Resolve to DOM element (synchronous — uses cache)
const el = marco.xpath.resolve("chatBox");
if (el) {
    el.click();
}

// Resolve all matching elements
const items = marco.xpath.resolveAll("listItems");

// Refresh cache if XPaths changed at runtime
await marco.xpath.refreshCache();
\`\`\`

## XPath Utilities (Global)

The \`xpath\` project (\`standalone-scripts/xpath/\`) provides global utility functions available on \`window\`:

### \`getByXPath(expression, context?)\`

Evaluate an XPath expression and return the first matching element.

\`\`\`javascript
const el = getByXPath("//button[contains(text(), 'Submit')]");
\`\`\`

### \`getAllByXPath(expression, context?)\`

Return all matching elements as an array.

\`\`\`javascript
const buttons = getAllByXPath("//button[@class='action']");
\`\`\`

### \`findElement(options)\`

Multi-method element search with fallback chain:

\`\`\`javascript
const el = findElement({
    xpath: "//div[@id='main']",
    selector: "#main",
    text: "Main Content",
    timeout: 5000,
});
\`\`\`

Search order: XPath → CSS selector → text content → timeout.

### \`reactClick(element)\`

Perform a React-compatible synthetic click that triggers React's event system:

\`\`\`javascript
const btn = getByXPath("//button[@data-action='save']");
if (btn) {
    reactClick(btn);
}
\`\`\`

This dispatches \`mousedown\`, \`mouseup\`, and \`click\` events with proper bubbling to ensure React's synthetic event system detects the interaction.

## Waiting for Dynamic DOM

Use \`marco.utils.waitForElement()\` for elements that load asynchronously:

\`\`\`javascript
// Wait for element by CSS selector
const el = await marco.utils.waitForElement({
    selector: "#dynamic-content",
    timeoutMs: 10000,
    intervalMs: 200,
});

// Wait for element by XPath
const el2 = await marco.utils.waitForElement({
    selector: "//div[@data-loaded='true']",
    useXPath: true,
    timeoutMs: 5000,
});
\`\`\`

## Polling Patterns

For conditions beyond element presence:

\`\`\`javascript
// Poll until a condition is truthy
const result = await marco.utils.pollUntil(
    () => document.querySelector("#status")?.textContent === "Ready" ? true : null,
    { timeoutMs: 15000, intervalMs: 500 },
);
\`\`\`

## Retry Patterns

For flaky operations (network, DOM race conditions):

\`\`\`javascript
const data = await marco.utils.withRetry(
    async () => {
        const el = getByXPath("//span[@class='balance']");
        if (!el) throw new Error("Element not found");
        return el.textContent;
    },
    {
        maxAttempts: 3,
        delayMs: 1000,
        backoffMultiplier: 2,
        onRetry: (attempt, err) => console.log(\`Retry \${attempt}:\`, err),
    },
);
\`\`\`

## Common XPath Patterns

| Pattern | XPath |
|---------|-------|
| Button by text | \`//button[contains(text(), 'Save')]\` |
| Input by placeholder | \`//input[@placeholder='Enter name']\` |
| Element by class | \`//div[contains(@class, 'sidebar')]\` |
| Nth child | \`(//li[@class='item'])[3]\` |
| Parent traversal | \`//span[@id='label']/..\` |
| Attribute contains | \`//*[contains(@data-id, 'prefix')]\` |
| Text exact match | \`//*[text()='Exact Text']\` |
`,

  // 08-config-and-theme.md
  `# 08 — Config & Theme System

> Runtime configuration injection, theme variables, and LESS pipeline.

---

## Runtime Config Injection

JSON config files declared in \`instruction.ts\` are injected as \`window\` globals before JavaScript executes:

\`\`\`typescript
// instruction.ts
configs: [
    { file: "macro-looping-config.json", key: "config", injectAs: "__MARCO_CONFIG__" },
    { file: "macro-theme.json", key: "theme", injectAs: "__MARCO_THEME__" },
],
\`\`\`

At injection time, the extension:
1. Fetches the JSON file from \`chrome.runtime.getURL()\`
2. Injects it as a window global: \`window.__MARCO_CONFIG__ = { ... }\`
3. The script can then read it directly or via \`marco.config.get(key)\`

## Config File Structure

### \`macro-looping-config.json\` (Example)

\`\`\`json
{
    "loopEnabled": true,
    "maxRetries": 5,
    "delayBetweenLoopsMs": 3000,
    "targetUrl": "https://example.com/*",
    "features": {
        "autoScroll": true,
        "captureScreenshots": false
    }
}
\`\`\`

## Reading Config at Runtime

\`\`\`javascript
// Via window global (synchronous, available immediately after injection)
const config = window.__MARCO_CONFIG__;
const maxRetries = config.maxRetries;

// Via SDK (asynchronous, fetches from storage)
const maxRetries2 = await marco.config.get("maxRetries");
const allConfig = await marco.config.getAll();
\`\`\`

## Updating Config at Runtime

\`\`\`javascript
// Persist + broadcast change
await marco.config.set("maxRetries", 10);

// Listen for changes (from any source)
marco.config.onChange((key, value) => {
    console.log(\`Config changed: \${key} = \${value}\`);
    if (key === "loopEnabled" && !value) {
        stopLoop();
    }
});
\`\`\`

## Theme System

### \`macro-theme.json\` Structure

\`\`\`json
{
    "presets": {
        "dark": {
            "colors": {
                "primary": "#6366f1",
                "background": "#0a0a0f",
                "surface": "#1a1a2e",
                "text": "#e2e8f0",
                "success": "#22c55e",
                "warning": "#eab308",
                "error": "#ef4444",
                "status": {
                    "errorBg": "#4a1515",
                    "errorPale": "#fca5a5",
                    "warningBg": "#3d3d1e",
                    "successBg": "#1a3d33"
                },
                "toast": {
                    "info": { "bg": "#1a1a3d", "border": "#3b82f6", "text": "#93c5fd" }
                }
            }
        }
    }
}
\`\`\`

### Theme Injection

\`\`\`javascript
// Injected as window global
const theme = window.__MARCO_THEME__;
const darkColors = theme.presets.dark.colors;

// The notify module automatically reads theme colors for toast styling
marco.notify.info("Themed toast!");
\`\`\`

## LESS Pipeline

### Variables → CSS Custom Properties

LESS source files (\`less/{name}.less\`) can define variables that map to CSS custom properties:

\`\`\`less
// less/macro-looping.less
@primary: #6366f1;
@bg-surface: #1a1a2e;

.marco-panel {
    background: @bg-surface;
    border-color: @primary;
}
\`\`\`

Compiled to \`dist/{name}.css\` and injected into \`<head>\` before JavaScript runs.

### Template System

Templates in \`templates/\` are compiled to \`dist/templates.json\` and injected as \`window.__MARCO_TEMPLATES__\`:

\`\`\`javascript
const tpl = window.__MARCO_TEMPLATES__;
const panelHtml = tpl["control-panel"];  // Key = filename without extension
document.body.insertAdjacentHTML("beforeend", panelHtml);
\`\`\`

## Config Binding in Scripts

Scripts can declare which config they depend on via \`configBinding\` and \`themeBinding\`:

\`\`\`typescript
scripts: [
    {
        file: "macro-looping.js",
        order: 1,
        configBinding: "config",   // Ensures __MARCO_CONFIG__ is injected first
        themeBinding: "theme",     // Ensures __MARCO_THEME__ is injected first
        isIife: true,
    },
],
\`\`\`

The injection pipeline guarantees that bound configs are available as window globals before the script executes.
`,

  // 09-testing-and-debugging.md
  `# 09 — Testing & Debugging

> How to test scripts, debug in DevTools, and troubleshoot common issues.

---

## Testing in Browser Console

You can test SDK methods directly in the browser console when the extension is active:

\`\`\`javascript
// Check SDK is loaded
console.log(marco.version);

// Test auth
const token = await marco.auth.getToken();
console.log("Token:", token?.substring(0, 20) + "...");

// Test config
const config = await marco.config.getAll();
console.log("Config:", config);

// Test XPath
const el = marco.xpath.resolve("chatBox");
console.log("Chat box:", el);

// Test notifications
marco.notify.info("Test notification");
marco.notify.error("Test error", { noStop: true });
\`\`\`

## DevTools Debugging

### Finding Injected Scripts

1. Open Chrome DevTools (\`F12\` or \`Ctrl+Shift+I\`)
2. Go to **Sources** tab
3. Look under **Content Scripts** → your extension ID
4. Or search for your script by filename (\`Ctrl+P\` → \`macro-looping.js\`)

### Setting Breakpoints

Since scripts run in MAIN world, they appear in the page's JavaScript context (not under Content Scripts). Search for your IIFE function names or unique string literals.

### Console Filtering

Filter console output by prefix:

\`\`\`
[marco-sdk]         — SDK internal logs
[macro-controller]  — Macro controller logs
[xpath]             — XPath utility logs
\`\`\`

## Log Conventions

Use consistent prefixes for all console output:

\`\`\`javascript
const TAG = "[my-project]";

console.log(TAG, "Initialized");
console.warn(TAG, "Config missing, using defaults");
console.error(TAG, "Failed to load:", error);
\`\`\`

## Common Errors and Fixes

### 1. \`window.marco is undefined\`

**Cause**: Your script loaded before the SDK.  
**Fix**: Ensure \`dependencies: ["marco-sdk"]\` in your \`instruction.ts\` and \`loadOrder\` is higher than 0.

### 2. \`Timeout waiting for AUTH_GET_TOKEN\`

**Cause**: Content script relay not installed, or extension not active on this page.  
**Fix**: Check that the page URL matches the extension's \`matches\` pattern. Verify the extension is enabled.

### 3. CSP blocks script injection

**Cause**: The website's Content Security Policy blocks inline scripts.  
**Fix**: The extension has a CSP fallback that injects via \`<script>\` element. If that also fails, the script cannot run on that page.

### 4. DOM element not found

**Cause**: Element hasn't rendered yet (SPA dynamic content).  
**Fix**: Use \`marco.utils.waitForElement()\` or \`marco.utils.pollUntil()\` instead of immediate DOM queries.

### 5. Config not available at script start

**Cause**: Script executes before config injection completes.  
**Fix**: Set \`configBinding\` in your instruction's script entry to ensure the config is injected first.

### 6. Duplicate injection

**Cause**: Script injected multiple times on navigation.  
**Fix**: Add an idempotency guard at the top of your script:

\`\`\`javascript
if (window.__MY_PROJECT_LOADED__) return;
window.__MY_PROJECT_LOADED__ = true;
\`\`\`

## Diagnostic Tools

### Auth Diagnostics

\`\`\`javascript
const diag = marco.auth.getLastAuthDiag();
console.log("Auth source:", diag?.source);
console.log("Duration:", diag?.durationMs + "ms");
console.log("Bridge outcome:", diag?.bridgeOutcome);
\`\`\`

### Recent Errors

\`\`\`javascript
const errors = marco.notify.getRecentErrors();
console.table(errors);
\`\`\`

### Extension Health Check

\`\`\`javascript
// Probe workspace API to verify connectivity
const resp = await marco.api.workspace.probe();
console.log("API health:", resp.ok ? "✅" : "❌", resp.status);
\`\`\`
`,

  // 10-examples.md
  `# 10 — Complete Examples

> Step-by-step walkthroughs for building new projects.

---

## Example A: Minimal Project (Single JS, No Config)

A simple script that monitors a page element and logs changes.

### Step 1: Create project folder

\`\`\`
standalone-scripts/page-monitor/
├── src/
│   ├── index.ts
│   └── instruction.ts
└── README.md
\`\`\`

### Step 2: \`src/instruction.ts\`

\`\`\`typescript
import type { SeedBlock } from "../../marco-sdk/src/instruction";

export interface ProjectInstruction {
    schemaVersion: string;
    name: string;
    displayName: string;
    version: string;
    description: string;
    world: "MAIN" | "ISOLATED";
    dependencies: string[];
    loadOrder: number;
    seed: SeedBlock;
    assets: {
        css: Array<{ file: string; inject: "head" }>;
        configs: Array<{ file: string; key: string; injectAs?: string }>;
        scripts: Array<{ file: string; order: number; configBinding?: string; themeBinding?: string; isIife?: boolean }>;
        templates: Array<{ file: string; injectAs?: string }>;
        prompts: Array<{ file: string }>;
    };
}

const instruction: ProjectInstruction = {
    schemaVersion: "1.0",
    name: "page-monitor",
    displayName: "Page Monitor",
    version: "1.0.0",
    description: "Monitor page elements and log changes",
    world: "MAIN",
    dependencies: ["xpath"],
    loadOrder: 3,
    seed: {
        id: "default-page-monitor",
        seedOnInstall: true,
        isRemovable: true,
        autoInject: false,
        runAt: "document_idle",
        cookieBinding: "lovable-session-id.id",
        targetUrls: [
            { pattern: "https://lovable.dev/projects/*", matchType: "glob" },
            { pattern: "https://*.lovable.app/*", matchType: "glob" },
            { pattern: "https://*.lovableproject.com/*", matchType: "glob" },
        ],
        cookies: [],
        settings: {},
    },
    assets: {
        css: [],
        configs: [],
        scripts: [
            { file: "page-monitor.js", order: 1, isIife: true },
        ],
        templates: [],
        prompts: [],
    },
};

export default instruction;
\`\`\`

### Step 4: \`src/index.ts\`

\`\`\`typescript
(function pageMonitor() {
    // Idempotency guard
    if ((window as any).__PAGE_MONITOR_LOADED__) return;
    (window as any).__PAGE_MONITOR_LOADED__ = true;

    const TAG = "[page-monitor]";

    async function init() {
        console.log(TAG, "Initializing v1.0.0");

        // Wait for the target element
        const target = await marco.utils.waitForElement({
            selector: "#content",
            timeoutMs: 10000,
        });

        if (!target) {
            console.warn(TAG, "Target element not found");
            marco.notify.warning("Page Monitor: target element not found");
            return;
        }

        // Set up mutation observer
        const observer = new MutationObserver((mutations) => {
            for (const mutation of mutations) {
                console.log(TAG, "DOM changed:", mutation.type, mutation.target);
            }
        });

        observer.observe(target, {
            childList: true,
            subtree: true,
            characterData: true,
        });

        console.log(TAG, "Monitoring started");
        marco.notify.success("Page Monitor active");
    }

    init().catch((err) => {
        console.error(TAG, "Init failed:", err);
        marco.notify.error("Page Monitor failed: " + err.message);
    });
})();
\`\`\`

### Step 5: Add build script

In root \`package.json\`:

\`\`\`json
{
    "scripts": {
        "build:page-monitor": "vite build --config vite.config.page-monitor.ts"
    }
}
\`\`\`

### Step 6: Build and deploy

\`\`\`bash
npm run build:page-monitor
npm run build:ext
\`\`\`

The project is automatically discovered, included in \`seed-manifest.json\`, and deployed to \`chrome-extension/dist/projects/scripts/page-monitor/\`.

---

## Example B: Full Project (CSS, Config, Theme, Templates)

A dashboard overlay with customizable theme and config.

### Step 1: Create project folder

\`\`\`
standalone-scripts/dashboard-overlay/
├── src/
│   ├── index.ts
│   └── instruction.ts
├── less/
│   └── dashboard-overlay.less
├── templates/
│   └── panel.html
└── README.md
\`\`\`

### Step 2: \`src/instruction.ts\`

\`\`\`typescript
import type { SeedBlock } from "../../marco-sdk/src/instruction";

// (ProjectInstruction interface same as Example A)

const instruction: ProjectInstruction = {
    schemaVersion: "1.0",
    name: "dashboard-overlay",
    displayName: "Dashboard Overlay",
    version: "1.0.0",
    description: "Customizable dashboard overlay with credit display",
    world: "MAIN",
    dependencies: ["xpath"],
    loadOrder: 4,
    seed: {
        id: "default-dashboard-overlay",
        seedOnInstall: true,
        isRemovable: true,
        autoInject: false,
        runAt: "document_idle",
        cookieBinding: "lovable-session-id.id",
        targetUrls: [
            { pattern: "https://lovable.dev/projects/*", matchType: "glob" },
            { pattern: "https://*.lovable.app/*", matchType: "glob" },
            { pattern: "https://*.lovableproject.com/*", matchType: "glob" },
        ],
        cookies: [],
        settings: {},
        configSeedIds: {
            config: "default-dashboard-overlay-config",
            theme: "default-dashboard-overlay-theme",
        },
    },
    assets: {
        css: [
            { file: "dashboard-overlay.css", inject: "head" },
        ],
        configs: [
            { file: "dashboard-config.json", key: "config", injectAs: "__DASHBOARD_CONFIG__" },
            { file: "dashboard-theme.json", key: "theme", injectAs: "__DASHBOARD_THEME__" },
        ],
        scripts: [
            {
                file: "dashboard-overlay.js",
                order: 1,
                configBinding: "config",
                themeBinding: "theme",
                isIife: true,
            },
        ],
        templates: [
            { file: "templates.json", injectAs: "__DASHBOARD_TEMPLATES__" },
        ],
        prompts: [],
    },
};

export default instruction;
\`\`\`

### Step 4: Config files

**\`dashboard-config.json\`**:
\`\`\`json
{
    "refreshIntervalMs": 30000,
    "showCredits": true,
    "position": "bottom-right"
}
\`\`\`

**\`dashboard-theme.json\`**:
\`\`\`json
{
    "presets": {
        "dark": {
            "colors": {
                "panelBg": "#1a1a2e",
                "panelBorder": "#6366f1",
                "text": "#e2e8f0"
            }
        }
    }
}
\`\`\`

### Step 5: LESS stylesheet

\`\`\`less
// less/dashboard-overlay.less
@panel-bg: #1a1a2e;
@panel-border: #6366f1;
@text-color: #e2e8f0;

.dashboard-overlay {
    position: fixed;
    bottom: 12px;
    right: 12px;
    z-index: 99998;
    background: @panel-bg;
    border: 1px solid @panel-border;
    border-radius: 8px;
    padding: 12px;
    color: @text-color;
    font-family: monospace;
    font-size: 12px;
}
\`\`\`

### Step 6: Template

\`\`\`html
<!-- templates/panel.html -->
<div class="dashboard-overlay" id="dashboard-panel">
    <div class="dashboard-header">Dashboard</div>
    <div class="dashboard-credits">Credits: <span id="credit-display">--</span></div>
    <button id="dashboard-refresh">↻ Refresh</button>
</div>
\`\`\`

### Step 7: \`src/index.ts\`

\`\`\`typescript
(function dashboardOverlay() {
    if ((window as any).__DASHBOARD_OVERLAY_LOADED__) return;
    (window as any).__DASHBOARD_OVERLAY_LOADED__ = true;

    const TAG = "[dashboard-overlay]";
    const config = (window as any).__DASHBOARD_CONFIG__ || {};
    const templates = (window as any).__DASHBOARD_TEMPLATES__ || {};

    async function init() {
        console.log(TAG, "Initializing v1.0.0");

        // Inject template
        const panelHtml = templates["panel"];
        if (panelHtml) {
            document.body.insertAdjacentHTML("beforeend", panelHtml);
        }

        // Fetch and display credits
        if (config.showCredits) {
            await refreshCredits();
            setInterval(refreshCredits, config.refreshIntervalMs || 30000);
        }

        // Refresh button
        const refreshBtn = document.getElementById("dashboard-refresh");
        if (refreshBtn) {
            refreshBtn.addEventListener("click", refreshCredits);
        }

        marco.notify.success("Dashboard overlay loaded");
    }

    async function refreshCredits() {
        try {
            const resp = await marco.api.credits.fetchWorkspaces();
            if (resp.ok) {
                const display = document.getElementById("credit-display");
                if (display) {
                    display.textContent = JSON.stringify(resp.data);
                }
            }
        } catch (err) {
            console.error(TAG, "Credit fetch failed:", err);
        }
    }

    init().catch((err) => {
        console.error(TAG, "Init failed:", err);
        marco.notify.error("Dashboard overlay failed: " + err.message);
    });
})();
\`\`\`

---

## Checklist for New Projects

- [ ] Created \`standalone-scripts/{name}/\` with \`src/index.ts\` and \`src/instruction.ts\`
- [ ] \`instruction.ts\` includes \`schemaVersion\`, \`seed\` block, and all asset declarations
- [ ] Added \`build:{name}\` script to root \`package.json\`
- [ ] Set \`dependencies\` in instruction.ts (at minimum: \`["xpath"]\`)
- [ ] Set \`loadOrder\` higher than all dependencies
- [ ] Added idempotency guard in \`src/index.ts\`
- [ ] Used \`[{name}]\` prefix for all console logs
- [ ] Tested in browser console that \`marco.*\` APIs work
- [ ] Verified the project appears in \`seed-manifest.json\` after build
`,

] as const;
