/**
 * Marco Extension — Shared Constants (Re-export)
 *
 * Canonical source: src/shared/constants.ts
 */
export {
    EXTENSION_VERSION,
    STORAGE_KEY_ACTIVE_PROJECT,
    STORAGE_KEY_ALL_PROJECTS,
    STORAGE_KEY_ALL_SCRIPTS,
    STORAGE_KEY_ALL_CONFIGS,
    STORAGE_KEY_CONFIG_OVERRIDES,
    STORAGE_KEY_STATE,
    STORAGE_KEY_FIRST_RUN,
    STORAGE_KEY_LEGACY_PRUNED,
    MAX_SCRIPT_SIZE_BYTES,
    MAX_CONFIG_SIZE_BYTES,
    MAX_REGEX_LENGTH,
    LOG_PAGE_SIZE,
    KEEPALIVE_INTERVAL_MINUTES,
    DEFAULT_TIMEOUT_MS,
    MAX_RETRY_COUNT,
    DEFAULT_PROJECT_ID,
    DEFAULT_GLOBAL_VAR_NAME,
} from "../../../src/shared/constants";
